# Generated by Django 3.0.6 on 2020-06-01 07:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_employees_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='age',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(20, 'Invalid age'), django.core.validators.MaxValueValidator(70, 'Invalid age')], verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MinLengthValidator(30)], verbose_name='User Name'),
        ),
    ]
